# Generated by Django 4.1.7 on 2023-02-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invista', '0002_investimento_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investimento',
            name='nivel',
        ),
    ]
